# Generated by Django 6.1.2 on 2026-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_update_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Python Developer currently working at M7 Technology. Experienced in developing backend services, RESTful APIs, and database-driven web solutions using Python, Django, Flask, and PostgreSQL. Previously worked at Levantare Technology.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(default='Python Developer at M7 Technology | Specializing in Django Backend & Full Stack Development', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Python Developer | Django & Full Stack Developer', max_length=255),
        ),
    ]
